# Generated by Django 4.2.28 on 2026-04-22 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodPalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_subject', models.CharField(db_index=True, max_length=120)),
                ('anon_id', models.CharField(blank=True, default='', max_length=64)),
                ('persona_id', models.CharField(choices=[('logic_brother', '逻辑派的邻家哥哥'), ('empathy_sister', '共情派的知心学姐'), ('insight_mentor', '深挖派的心理学前辈')], max_length=32)),
                ('selected_model', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('starting', '开始中'), ('active', '进行中'), ('ending', '结束处理中'), ('summary_pending', '等待摘要确认'), ('closed', '已关闭')], default='starting', max_length=24)),
                ('timeout_seconds', models.PositiveIntegerField(default=1800)),
                ('summary_draft', models.TextField(blank=True, default='')),
                ('summary_final', models.TextField(blank=True, default='')),
                ('summary_action', models.CharField(blank=True, choices=[('', '未处理'), ('saved', '已保存'), ('destroyed', '已销毁')], default='', max_length=16)),
                ('close_reason', models.CharField(blank=True, choices=[('', '未结束'), ('user_ended', '用户主动结束'), ('idle_timeout', '超时自动结束')], default='', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moodpal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moodpal_sessions',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='moodpal_ses_status_dfe26e_idx'), models.Index(fields=['usage_subject', 'created_at'], name='moodpal_ses_usage_s_1bc2d5_idx')],
            },
        ),
    ]
