# Generated by Django 4.2.28 on 2026-04-22 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodpal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodPalSessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('summary_generated', '摘要已生成'), ('summary_saved', '摘要已保存'), ('summary_destroyed', '摘要已销毁'), ('raw_messages_destroyed', '原始消息已销毁')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='moodpal.moodpalsession')),
            ],
            options={
                'db_table': 'moodpal_session_events',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['session', 'event_type', 'created_at'], name='moodpal_ses_session_7c33c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MoodPalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], max_length=16)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='moodpal.moodpalsession')),
            ],
            options={
                'db_table': 'moodpal_messages',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='moodpal_mes_session_29435b_idx')],
            },
        ),
    ]
