# Generated by Django 4.2.28 on 2026-05-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodpal', '0004_alter_moodpalsession_persona_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Da',
            fields=[
            ],
            options={
                'verbose_name': 'MoodPal Analytics',
                'verbose_name_plural': 'MoodPal Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('moodpal.moodpalsession',),
        ),
        migrations.AlterField(
            model_name='moodpalsession',
            name='persona_id',
            field=models.CharField(choices=[('master_guide', '全能主理人'), ('logic_brother', '逻辑派的邻家哥哥'), ('empathy_sister', '共情派的知心学姐'), ('insight_mentor', '深挖派的心理学前辈'), ('spirit_companion', '小猫仙橘')], max_length=32),
        ),
    ]
