# Generated by Django 4.2.30 on 2026-04-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('era', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('background', models.TextField(blank=True)),
                ('major_works', models.JSONField(default=list)),
                ('viewpoints', models.JSONField(default=dict)),
                ('language_style', models.JSONField(default=dict)),
                ('representative_articles', models.JSONField(default=list)),
                ('temporal_constraints', models.JSONField(default=dict)),
                ('message_count', models.IntegerField(default=0)),
                ('speaking_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'roundtable_characters',
                'ordering': ['speaking_order'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('setup', '配置中'), ('ready', '就绪'), ('active', '进行中'), ('paused', '已暂停'), ('finished', '已结束')], default='setup', max_length=20)),
                ('user_role', models.CharField(choices=[('moderator', '主持人'), ('participant', '参与者'), ('observer', '旁观者')], default='moderator', max_length=20)),
                ('character_limit', models.IntegerField(default=200)),
                ('max_rounds', models.IntegerField(default=100)),
                ('current_round', models.IntegerField(default=0)),
                ('current_speaker', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roundtable_discussions',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='roundtable.character')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='roundtable.discussion')),
            ],
            options={
                'db_table': 'roundtable_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='roundtable.discussion'),
        ),
    ]
