# Generated by Django 4.2.30 on 2026-04-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundtable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='consecutive_mentions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='host_token_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='host_token_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='player_token_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='player_token_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='token_timeout_seconds',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='user_role',
            field=models.CharField(choices=[('host', '主持人'), ('participant', '参与者'), ('observer', '旁观者')], default='host', max_length=20),
        ),
    ]
