# Generated by Django 4.2.30 on 2026-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundtable', '0002_character_consecutive_mentions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='init_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='player_waiting_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='player_mentioned_character',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read_but_no_reply',
            field=models.BooleanField(default=False),
        ),
    ]
