# Generated by Django 4.2.30 on 2026-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundtable', '0003_discussion_init_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='max_rounds',
            field=models.IntegerField(default=30),
        ),
    ]
