# Generated by Django 4.2.28 on 2026-04-19 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roundtable', '0007_character_unique_per_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('private', '仅自己可见')], default='public', max_length=10),
        ),
    ]
