# Generated by Django 4.2.28 on 2026-04-20 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roundtable', '0008_discussion_owner_discussion_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='usage_subject',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='TokenUsageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_key', models.CharField(db_index=True, max_length=120)),
                ('subject_type', models.CharField(choices=[('user', '登录用户'), ('anon', '匿名用户')], max_length=10)),
                ('anon_id', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(default='unknown', max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to='roundtable.discussion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roundtable_token_usage_ledger',
                'indexes': [models.Index(fields=['subject_key', 'created_at'], name='roundtable__subject_62fd63_idx'), models.Index(fields=['source', 'created_at'], name='roundtable__source_73b97d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenQuotaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_key', models.CharField(max_length=120, unique=True)),
                ('subject_type', models.CharField(choices=[('user', '登录用户'), ('anon', '匿名用户')], max_length=10)),
                ('anon_id', models.CharField(blank=True, default='', max_length=64)),
                ('used_tokens', models.BigIntegerField(default=0)),
                ('quota_limit', models.BigIntegerField(default=0)),
                ('last_warn_level', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_quota_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roundtable_token_quota_states',
                'indexes': [models.Index(fields=['subject_type', 'updated_at'], name='roundtable__subject_c8ed5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuotaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_key', models.CharField(db_index=True, max_length=120)),
                ('subject_type', models.CharField(choices=[('user', '登录用户'), ('anon', '匿名用户')], max_length=10)),
                ('anon_id', models.CharField(blank=True, default='', max_length=64)),
                ('contact', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', '待处理'), ('in_progress', '处理中'), ('resolved', '已处理')], default='new', max_length=20)),
                ('used_tokens', models.BigIntegerField(default=0)),
                ('quota_limit', models.BigIntegerField(default=0)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roundtable_quota_feedback',
                'indexes': [models.Index(fields=['status', 'created_at'], name='roundtable__status_8a0114_idx'), models.Index(fields=['subject_key', 'created_at'], name='roundtable__subject_5d8fb1_idx')],
            },
        ),
    ]
